name = "minsnote-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ALLOWED_ORIGIN = "https://jinwonmin.github.io"

[[kv_namespaces]]
binding = "VIEWS"
id = "081c007b875a4a1a8b8d45fa2e79386f"

[[d1_databases]]
binding = "DB"
database_name = "minsnote-db"
database_id = "8333d453-27a7-4c3f-83ab-a72f8b0d5620"
